name: Expo Web Build

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.20

      - name: Install dependencies
        run: npm ci

      - name: Build Expo Web
        run: npx expo build:web --output-dir web-build
